language: r
cache:
  - packages: true
  - $HOME/.ccache

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - ccache
     - g++-7

before_install:
  - mkdir -p $HOME/.R
  - echo -e 'CXX_STD = CXX14\n\nVER=-7\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  - echo "CXX14 = g++$(VER) -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> $HOME/.R/Makevars
  - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf

install:
    - Rscript ./scripts/r/install_packages.r 

script:
    - Rscript ./tests/testthat.R $TRAVIS_BUILD_DIR

notifications:
  email:
    if: branch=master
    on_failure: change
    on_success: change
    recipients:
      - btskinner@coe.ufl.edu