language: r
cache: packages

env:
  global:
    - MAKEFLAGS="-j 2"
    
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

install:
  - R -e "install.packages('rstan')"
  - Rscript ./scripts/r/install_packages.r 

script:
  - Rscript ./tests/testthat.R $TRAVIS_BUILD_DIR

notifications:
  email:
    if: branch=master
    on_failure: change
    on_success: change
    recipients:
      - btskinner@coe.ufl.edu