language: r

install:
    - Rscript ./scripts/r/install_packages.r 

script:
    - Rscript ./tests/testthat.r $TRAVIS_BUILD_DIR

notifications:
  email:
    if: branch=master
    on_failure: change
    on_success: change
    recipients:
      - btskinner@coe.ufl.edu