language: r
cache:
  - packages: true
  - $HOME/.ccache

addons:
  apt:
    packages:
     - ccache

before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf

install:
    - Rscript ./scripts/r/install_packages.r 

script:
    - Rscript ./tests/testthat.R $TRAVIS_BUILD_DIR

notifications:
  email:
    if: branch=master
    on_failure: change
    on_success: change
    recipients:
      - btskinner@coe.ufl.edu